version: '3.8'
services:
  app:
    build: .
    container_name: nest_app
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql:8
    container_name: user_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ${DB_DATABASE} 
      MYSQL_USER: ${DB_USERNAME}      
      MYSQL_PASSWORD: ${DB_PASSWORD}  
    ports:
      - "${DB_PORT}:${DB_PORT}" 
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: